export type UnavailableReason =
  | "PREVIOUS_AND_TARGET_UNAVAILABLE"
  | "PREVIOUS_UNAVAILABLE"
  | "PREVIOUS_EQUALS_TARGET"
  | "TARGET_UNAVAILABLE"
  | "INITIALIZATION"
  | "INCEPTION"
  | "INITIALIZATION_UNVERIFIED"
  | "REMOVED";
